FROM ubuntu:24.04

# Install requisites
RUN apt update && \
    apt install -y \
    cmake \
    ninja-build \
    gdb-multiarch \
    gcc-aarch64-linux-gnu \
    g++-aarch64-linux-gnu \
    libopencv-dev